package michael.findata.service;

public enum EnumStyleRefreshFinData {
	FiLL_ALL_RECENT,
	FILL_MISSING_ACCORDING_TO_REPORT_PUBLICATION_DATE,
	FILL_RECENT_ACCORDING_TO_REPORT_PUBLICATION_DATE,
	FILL_GIVEN
}
